version: "3"

services:
  app:
    image: registry.dev.credimovil.pe/${IMAGENAME}:${CI_PIPELINE_ID}
    build: .
    restart: always
    networks:
     - swarm-dev
    ports:
      - "${PORTSALIDA}:${PORTDOCKER}"
    deploy:
        mode: replicated
        replicas: 1
        # placement:
        #   constraints:
        #     - node.labels.name == ${NODO}
        resources:
          reservations:
            cpus: '0.3'
            memory: 200M  # Set the memory reservation here
          limits:
            cpus: '0.3'
            memory: 300M  # Set the memory limit here
    environment:
      - TZ=America/Lima
      - PORT=${PORT}
      - BD_CORE_HOST=${BD_CORE_HOST}
      - BD_CORE_PORT=${BD_CORE_PORT}
      - BD_CORE_DATABASE=${BD_CORE_DATABASE}
      - BD_CORE_USERNAME=${BD_CORE_USERNAME}
      - BD_CORE_PASSWORD=${BD_CORE_PASSWORD}
      
networks:
  swarm-dev:
    external: true
  swarm-qa:
    external: true
  swarm-prod:
    external: true
