export type CreditPaymentDTO = {
  cod_cre: string;
  num_cuo: number;
  lug_rec: string;
  fec_pag: string;
  hor_pag: string;
  fec_doc: string;
  pago: number;
  pag_cap: number;
  pag_int: number;
  pag_seg: number;
  pag_seg_desgra: number;
  pag_mor: number;
  pag_itf: number;
  fec_reg: string;
  hor_reg: string;
  usu_reg: string;
  fec_reg_pag: string;
  tip_pagcuo: string;
  id_pagcre: string;
  fe_propre: string;
};
